### ISSUE TITLE
No disconnect function on MetaMask

### ISSUE THREAD

**Issue by frankye23** [vu3th/vue-dapp#109] opened 2022-12-23 02:20 UTC

**Comment by chnejohnson** [comment] 2022-12-23 03:15
@frankye23 It seems to work well on my side, please give me more information (code or video) for me to reproduce your situation.
https://user-images.githubusercontent.com/31992185/209263689-598c222d-4f44-4024-b193-7118f37cc1e9.mov

**Comment by frankye23** [comment] 2022-12-23 03:24
> @frankye23 It seems to work well on my side, please give me more information (code or video) for me to reproduce your situation.
> 
>  2022-12-23.11.13.04.mov

I'm having problem of calling open method of useBoard(), so i choose to use ethers to connect my wallet like below:
`
await window.ethereum.enable()
  provider = new ethers.providers.Web3Provider(window.ethereum)
`
After i call this method, i successfully open the window of metamask
![image](https://user-images.githubusercontent.com/92201847/209264473-370f05bc-37e3-4386-b64c-3ce8ef31f333.png)
and when i confirm the connect, this modal will just hide and nothing happen.When i refresh my page, metamask shows that i am connected, but isActivated is false and i cannot see my shortenAddress and balance.
By the way, i set autoconnect like this:
`
app.use(VueDapp,{
  autoConnect: true
})
`

**Comment by chnejohnson** [comment] 2022-12-23 04:00
Ok, when you refresh the page, the isActivated must be false and the wallet.status must be none, it means there is no data on your app.

The reason why you app doesn't trigger autoconnect is because autoconnect is initiated on Board.vue > onMounted().

So if you don't use Board.vue, you have to trigger autoconnect function on your app.

**Comment by frankye23** [comment] 2022-12-23 07:03
> ```js
> const { autoConnect } = useWallet()
> await autoConnect(connectors)
> ```

Sorry to ask, but In this code, what does connectors stands for?
How should i define it?

**Comment by chnejohnson** [comment] 2022-12-23 09:09
The connectors is from the built-in connector classes to implement a common interface between different wallet provider
```js
import {
  MetaMaskConnector,
  WalletConnectConnector,
  CoinbaseWalletConnector,
} from "vue-dapp";

const connectors = [
  new MetaMaskConnector({
    appUrl: "http://localhost:3000",
  }),
  new WalletConnectConnector({
    qrcode: true,
    rpc: {
      1: `https://mainnet.infura.io/v3/${infuraId}`,
      4: `https://rinkeby.infura.io/v3/${infuraId}`,
    },
  }),
  new CoinbaseWalletConnector({
    appName: "Vue Dapp",
    jsonRpcUrl: `https://mainnet.infura.io/v3/${infuraId}`,
  }),
];
```

> await window.ethereum.enable() provider = new ethers.providers.Web3Provider(window.ethereum)

But it seems that you don't use the built-in connector, so I think you have to write your own autoconnect function, you can refer to https://github.com/chnejohnson/vue-dapp/blob/be2bb15f976a81deb89f7573f04a289e9f4ed6f8/src/composables/useWallet.ts#L159-L174

**Comment by re2005** [comment] 2022-12-23 10:53
@chnejohnson I'm facing the same issue here, please check:

https://user-images.githubusercontent.com/2920357/209323458-4498f4dc-0448-4b73-88ff-345de9da19c5.mov

Once the flag is on localStorage and I refresh the flag goes away, and it auto-connects again.

**Comment by chnejohnson** [comment] 2022-12-23 11:23
@re2005 hmm....wired, if the localStorage has the item, it would not trigger autoConnect
https://github.com/chnejohnson/vue-dapp/blob/be2bb15f976a81deb89f7573f04a289e9f4ed6f8/src/composables/useWallet.ts#L159-L166

I guess whether a function is called before autoConnect and it removed the localStorage item. Help me to confirm that if there is a function trigger `connectWith` in App.vue or some hooks before `<vd-board>` mounted, because `connectWith` is the only function which would remove the localStorage item.

https://github.com/chnejohnson/vue-dapp/blob/be2bb15f976a81deb89f7573f04a289e9f4ed6f8/src/composables/useWallet.ts#L103

**Comment by re2005** [comment] 2022-12-24 20:15
@chnejohnson you are right. In my app I still not using the `autoConnect` DUO Gnosis safe. But I've also checked that you fixed completely the `Gnosis` Safe connector. So I'll migrate to use it. Thanks!

Is the DEMO already working on vercel ?

**Comment by chnejohnson** [comment] 2022-12-25 04:17
@re2005 Yeah, the DEMO is on https://vuedapp.vercel.app, working well on Gnosis Safe :)

**Comment by frankye23** [comment] 2022-12-26 03:28
> @re2005 Yeah, the DEMO is on https://vuedapp.vercel.app, working well with Gnosis Safe :)

I use the template here [vue3-dapp-starter.netlify.app/](https://vue3-dapp-starter.netlify.app/)
And it appears that when i connect my wallet, it has the problem i mentioned before:
![image](https://user-images.githubusercontent.com/92201847/209496162-e9112400-0e7e-43f6-ba96-d3401a84e993.png)
I wonder if there's some error?

**Comment by chnejohnson** [comment] 2022-12-26 11:48
@frankye23 there are some discussions about your problem. I haven't read every comment but there might be a good answer.

- https://github.com/MetaMask/metamask-extension/issues/10353
- https://github.com/MetaMask/metamask-extension/issues/8990

**Comment by Walletsuppport** [comment] 2023-01-21 13:47
> > @re2005 Yeah, the DEMO is on https://vuedapp.vercel.app, working well with Gnosis Safe :)
> 
> I use the template here [vue3-dapp-starter.netlify.app/](https://vue3-dapp-starter.netlify.app/)
> And it appears that when i connect my wallet, it has the problem i mentioned before:
> ![image](https://user-images.githubusercontent.com/92201847/209496162-e9112400-0e7e-43f6-ba96-d3401a84e993.png)
> I wonder if there's some error?

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by Walletsuppport** [comment] 2023-01-21 13:47
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by chnejohnson** [comment] 2024-01-28 09:51
Close this issue as vue-dapp has introduced a new version with breaking changes. If there is an issue, please open a new one.

**Closed by chnejohnson** 2024-01-28 09:51 UTC
